### ISSUE TITLE
how to persist numpy:ndarray 

### ISSUE THREAD

**Issue by zhangyunzhao** [pmem/issues#1024]
from nvm.pmemobj import PersistentObjectPool

data = np.load('/data/data/feature_100000_mat.npy')
with PersistentObjectPool('hello_world.pmem', flag='c') as pool:
    if pool.root is None:
    	pool.root = data

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/lib64/python2.7/site-packages/nvm/pmemobj/pool.py", line 795, in root
    oid = self.mm.persist(value)
  File "/usr/lib64/python2.7/site-packages/nvm/pmemobj/pool.py", line 491, in persist
    raise TypeError("Don't know how to persist {!r}".format(cls_str))
TypeError: Don't know how to persist 'numpy:ndarray'

**Comment by marcinslusarz** [comment]
This repo is for issues in PMDK. pynvm issues are tracked in pynvm repo (https://github.com/pmem/pynvm/issues ).
