### ISSUE TITLE
test: (py) null pmem dir crashes pycheck

### ISSUE THREAD

**Issue by kilobyte** [pmem/issues#1069]
master, tested on Debian buster and unstable.

`testconfig.py.example` says:
```
    #
    # For tests that require true persistent memory, set the path to
    # a directory on a PMEM-aware file system here.
    # Comment this line out if there's no actual persistent memory
    # available on this system.
    #

    'pmem_fs_dir': '/mnt/pmem',
```

Yet commenting it out causes pycheck to crash:
```
Traceback (most recent call last):
  File "./RUNTESTS.py", line 90, in <module>
    main()
  File "./RUNTESTS.py", line 86, in main
    sys.exit(_run_tests(config))
  File "./RUNTESTS.py", line 80, in _run_tests
    return futils.run_tests_common(testcases, config)
  File "/home/kilobyte/c/pmdk/src/test/unittest/futils.py", line 129, in run_tests_common
    t = t(config)
  File "/home/kilobyte/c/pmdk/src/test/unittest/basetest.py", line 139, in __init__
    self.ctxs = self._get_contexts()
  File "/home/kilobyte/c/pmdk/src/test/unittest/basetest.py", line 181, in _get_contexts
    self._ctx_attrs_init()
  File "/home/kilobyte/c/pmdk/src/test/unittest/basetest.py", line 159, in _ctx_attrs_init
    setattr(self, attr, base.factory(self.config, *ctx_val))
  File "/home/kilobyte/c/pmdk/src/test/unittest/context.py", line 276, in factory
    return [c(conf) for c in expand(*classes)]
  File "/home/kilobyte/c/pmdk/src/test/unittest/context.py", line 276, in <listcomp>
    return [c(conf) for c in expand(*classes)]
  File "/home/kilobyte/c/pmdk/src/test/unittest/context.py", line 330, in __init__
    self.dir = os.path.abspath(conf.pmem_fs_dir)
AttributeError: 'Config' object has no attribute 'pmem_fs_dir'
```

Likewise, obvious alternate values such as `None` cause similar crashes.

**Comment by kilobyte** [comment]
✓
