### ISSUE TITLE
test (py): pycheck crash with upstream valgrind (ie, no pmemcheck)

### ISSUE THREAD

**Issue by kilobyte** [pmem/issues#1070]
master, on Debian buster:

valgrind 3.14, unmodified, from the distribution — no pmemcheck.

Invoked via `cd src/test && make pycheck`

Instead of skipping the test, or at least reporting a fail, the test framework itself crashes:
```
obj_basic_integration/TEST1: SETUP	(medium/nonpmem/static_debug/pmemcheck)
Traceback (most recent call last):
  File "./RUNTESTS.py", line 90, in <module>
    main()
  File "./RUNTESTS.py", line 86, in main
    sys.exit(_run_tests(config))
  File "./RUNTESTS.py", line 80, in _run_tests
    return futils.run_tests_common(testcases, config)
  File "/home/kilobyte/pmdk/src/test/unittest/futils.py", line 130, in run_tests_common
    if t.enabled and t._execute():  # if test failed
  File "/home/kilobyte/pmdk/src/test/unittest/basetest.py", line 225, in _execute
    self.run(c)
  File "/home/kilobyte/pmdk/src/test/obj_basic_integration/TESTS.py", line 53, in run
    ctx.exec('obj_basic_integration', filepath)
  File "/home/kilobyte/pmdk/src/test/unittest/context.py", line 232, in exec
    and not self.valgrind.validate_log():
  File "/home/kilobyte/pmdk/src/test/unittest/valgrind.py", line 216, in validate_log
    with open(self.log_file, 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kilobyte/pmdk/src/test/obj_basic_integration/pmemcheck1.log'

```

**Comment by llugin** [comment]
fix merged into master, please verify

**Comment by kilobyte** [comment]
✓
