### ISSUE TITLE
pmembench/obj: perf.cfg crash

### ISSUE THREAD

**Issue by marcinslusarz** [pmem/issues#188]
```
$ cd src/benchmarks
$ edit perf.cfg: testfile -> /mnt/pmem/testfile
$ LD_LIBRARY_PATH=../debug ./pmembench perf.cfg
0.302255;661691.980338;0.305564;0.297526;0.304739;0.003418;1510;1144;76639;820.686907;1;200000;256;0;5;per-thread;basic;0;tx;0
0.322200;1241465.086977;0.327678;0.315785;0.323013;0.004063;1610;1169;85423;815.248306;2;200000;256;0;5;per-thread;basic;0;tx;0
0.318438;1884195.966795;0.325499;0.308211;0.320833;0.005879;1591;1109;160395;780.466912;3;200000;256;0;5;per-thread;basic;0;tx;0
0.331222;2415298.638883;0.365718;0.311971;0.324856;0.017636;1656;1132;12017432;25052.602943;4;200000;256;0;5;per-thread;basic;0;tx;0
0.395326;2529557.262689;0.484637;0.309714;0.399397;0.049012;1976;1103;28007265;69349.622279;5;200000;256;0;5;per-thread;basic;0;tx;0
0.453646;2645233.050616;0.548074;0.321262;0.470083;0.066536;2267;1126;28005932;92845.848361;6;200000;256;0;5;per-thread;basic;0;tx;0
0.532625;2628489.224495;0.612372;0.429450;0.551792;0.052063;2662;1126;28008105;114602.841224;7;200000;256;0;5;per-thread;basic;0;tx;0
0.580774;2754943.025138;0.703080;0.319254;0.617177;0.081405;2903;856;35998168;132181.781062;8;200000;256;0;5;per-thread;basic;0;tx;0
0.687071;2619816.376222;0.814367;0.419824;0.712419;0.084796;3434;1124;47991117;157081.905871;9;200000;256;0;5;per-thread;basic;0;tx;0
0.780495;2562477.284301;0.895118;0.601623;0.781276;0.062664;3902;1086;40006341;178963.281502;10;200000;256;0;5;per-thread;basic;0;tx;0

<libpmemobj>: <1> [memblock.c:139 run_block_offset] assertion failure: diff <= (((size_t)1024 * 256) - (40 * 8))

Thread 248 "pmembench" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe6ffd700 (LWP 8799)]
0x00007ffff6779418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6779418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff677b01a in __GI_abort () at abort.c:89
#2  0x00007ffff7bc9920 in out_fatal (file=<optimized out>, line=<optimized out>, func=<optimized out>, fmt=<optimized out>) at ../../src/../src/common/out.c:533
#3  0x00007ffff7bc2a2b in run_block_offset (m=0x7fffe6ffc920, pop=0x7ffec0000000, ptr=<optimized out>) at memblock.c:139
#4  0x00007ffff7bb6238 in get_mblock_from_alloc (pop=pop@entry=0x7ffec0000000, alloc=alloc@entry=0x7ffee4247040) at pmalloc.c:107
#5  0x00007ffff7bb65b6 in palloc_operation (pop=0x7ffec0000000, off=606367872, dest_off=dest_off@entry=0x7fffdc2e28a8, size=size@entry=0, constructor=constructor@entry=0x0, arg=arg@entry=0x0, 
    entries=0x7fffe6ffcc50, nentries=1) at pmalloc.c:312
#6  0x00007ffff7bb379b in obj_free (pop=<optimized out>, oidp=oidp@entry=0x7fffdc2e28a0) at obj.c:1303
#7  0x00007ffff7bb52f0 in pmemobj_free (oidp=0x7fffdc2e28a0) at obj.c:1548
#8  0x000000000041d2c9 in free_pmem (obj_bench=0x655b20 <obj_bench>, worker=0x3f25af8, idx=188926) at pmemobj_tx.c:442
#9  0x000000000041e47a in obj_tx_exit_worker (bench=0x65bc90, args=0x6679f0, worker=0x3f25af8) at pmemobj_tx.c:918
#10 0x0000000000407724 in thread_func (arg=0x3f25ae0) at benchmark_worker.c:100
#11 0x00007ffff6b146fa in start_thread (arg=0x7fffe6ffd700) at pthread_create.c:333
#12 0x00007ffff684ab5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) f 3
#3  0x00007ffff7bc2a2b in run_block_offset (m=0x7fffe6ffc920, pop=0x7ffec0000000, ptr=<optimized out>) at memblock.c:139
139             ASSERT(diff <= RUNSIZE);
(gdb) print diff
$1 = 602688256
```

**Comment by marcinslusarz** [comment]
... on 1.1-rc2

**Comment by plebioda** [comment]
It looks to me like an issue with zeroing pages in DAX. But need to double check this...

**Comment by plebioda** [comment]
I can't reproduce this on a ramdisk and kernel version 4.7-rc4. However I reproduced this on kernel version 4.4.8-200.fc22.x86_64. I think it confirms this is an issue with DAX. @marcinslusarz what is your kernel version ?

**Comment by marcinslusarz** [comment]
The above results are from kernel 4.4 (as packaged by Ubuntu 16.04). 
One more evidence it's a DAX issue is that pool prefaulting helps.

I'll test 4.6 soon.

**Comment by marcinslusarz** [comment]
I can't reproduce it on self-compiled kernel 4.6, so I think we can safely assume it's not a NVML bug.
